version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Set up tox tests
          command: |
            poetry self update
            poetry config http-basic.sensynehealth ${GEMFURY_DOWNLOAD_KEY} ''
            pip install --upgrade tox
      - restore_cache:
          keys:
            - v1-poetry-deps-{{ checksum "poetry.lock" }}
            - v1-poetry-deps-
      - run:
          name: Run tox tests
          command: tox -e py39
      - save_cache:
          key: v1-poetry-deps-{{ checksum "poetry.lock" }}
          paths:
            - .tox
  publish-pypi::
    docker:
      - image: cimg/python:3.9
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c8:78:26:3d:47:7a:16:5a:8e:ae:8f:2b:3e:58:b0:da"
      - checkout
      - run:
          name: Publish package to pypi
          command: poetry publish --build --username __token__ --password $PYPI_API_TOKEN
      - run:
          name: Create git tag
          command: pip install -U toml && git tag v$(python3 .circleci/parse_version.py)
      - run:
          name: Push git tag
          command: git push --tags
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: polaris-foundation
      - publish-pypi:
          context: polaris-foundation
          requires:
            - test
          filters:
            branches:
              only:
                - main
